version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: micro-catalog-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - micro-catalog

networks:
  micro-catalog:
    driver: bridge
